---
title: "testracefilter"
output: html_document
---

```{r}
install.packages("waffle")
```

```{r}
library(tidyverse)
library(waffle)

articles <- read_csv('../data/article_dat.csv')
```


```{r}

white <- c(
  "WHITE" = "White",
  "HISPANIC WHITE" = "White",
  "EUROPEAN AMERICAN" = "White",
  "CAUCASIAN OR WHITE" = "White",
  "WHITE, NON-HISPANIC" = "White",
  "CAUCASIAN" = "White",
  "NON-HISPANIC WHITE" = "White",
  "NH WHITE" = "White",
  "NON-HISPANIC WHITE AND ADDITIONAL RACE AND ETHNICITIES" = "White",
  "WHITE/CAUCASIAN"="White",
  "NON HISPANIC WHITES"="White",
  "CAUCASIANS"="White",
  "WHITE - NOT HISPANIC OR LATINO",
  "WHITE (NON-HISPANIC)"="White",
  "WHITE NON-HISPANIC"="White",
  "WHITE DONOR / WHITE RECIPIENT"="White",
  "U.S.-BORN, NON-HISPANIC WHITE;"="White",
  "NON-HISPANIC, WHITE"="White",
  "WHITE (OR CAUCASIAN)"="White",
  "WHITES"="White",
  "WHITE-NON-HISPANIC"="White",
  "NON-LATINA WHITE"="White",
  "WHITE OR CAUCASIAN"="White",
  "WHITE - NOT HISPANIC OR LATINO"="White",
  "NON HISPANIC WHITE"="White"

)

black <- c(
  "BLACK" = "Black or African American",
  "NON-HISPANIC BLACK" = "Black or African American",
  "AFRICAN AMERICAN" = "Black or African American",
  "BLACK/AFRICAN AMERICAN" = "Black or African American",
  "BLACK, NON-HISPANIC" = "Black or African American",
  "BLACK NON-HISPANIC" = "Black or African American",
  "BLACK OR AFRICAN AMERICAN" = "Black or African American",
  "AFRICAN AMERICANS" = "Black or African American",
  "AFRICAN-AMERICAN" = "Black or African American",
  "AFRICAN AMERICAN/BLACK" = "Black or African American",
  "U.S.-BORN, NON-HISPANIC BLACK" = "Black or African American",
  "NON-HISPANIC, BLACK" = "Black or African American",
  "BLACKS" = "Black or African American",
  "BLACK (NON-HISPANIC)" = "Black or African American",
  "NONBLACK" = "Black or African American",
  "AFRICAN AMERICAN OR BLACK" = "Black or African American",
  "BLACK DONOR / BLACK RECIPIENT" = "Black or African American",
  "BLACK DONOR / NONBLACK RECIPIENT" = "Black or African American",
  "AFRICAN AMERICAN, NON-HISPANIC" = "Black or African American",
  "AFRICAN-AMERICAN, NON-HISPANIC" = "Black or African American",
  "NON-HISPANIC BLACK/AFRICAN AMERICAN" = "Black or African American"
)

hispanic <- c(
  "HISPANIC" = "Hispanic or Latino",
  "HISPANIC WHITES" = "Hispanic or Latino",
  "HISPANIC/LATINA" = "Hispanic or Latino",
  "LATINA/HISPANIC" = "Hispanic or Latino",
  "US-BORN HISPANIC" = "Hispanic or Latino",
  "OTHER HISPANIC" = "Hispanic or Latino",
  "LATINA" = "Hispanic or Latino",
  "HISPANIC OR LATINO"="Hispanic or Latino",
  "LATINO"="Hispanic or Latino",
  "LATINO AMERICAN"="Hispanic or Latino",
  "HISPANIC OR LATINA"="Hispanic or Latino",
  "HISPANIC OR LATINO"="Hispanic or Latino",
  "HISPANIC (OF ANY RACE)"="Hispanic or Latino",
  "HISPANIC, SPANISH-SPEAKING"="Hispanic or Latino",
  "LATINA WHITE"="Hispanic or Latino",
  "FOREIGN-BORN HISPANIC"="Hispanic or Latino",
  "HISPANIC, NOT OTHERWISE SPECIFIED"="Hispanic or Latino",
  "HISPANIC DONOR / HISPANIC RECIPIENT"="Hispanic or Latino",
  "HISPANIC/LATINX"="Hispanic or Latino",
  "HISPANIC/LATINO/A"="Hispanic or Latino",
  "HISPANIC DONOR / NON-HISPANIC RECIPIENT"="Hispanic or Latino",
  "HISPANIC, ENGLISH-SPEAKING"="Hispanic or Latino",
  "HISPANIC AMERICAN"="Hispanic or Latino",
  "HISPANIC, LATINA"="Hispanic or Latino",
  "HISPANIC, ENGLISH-SPEAKING"="Hispanic or Latino",
  "HISPANIC OR LATINX"="Hispanic or Latino",
  "LATINA (SPANISH SPEAKING)"="Hispanic or Latino",
  "LATINA (ENGLISH-SPEAKING)"="Hispanic or Latino",
  "HISPANIC/LATINO"="Hispanic or Latino"
)

asian <- c(
  "ASIAN" = "Asian",
  "ASIAN AMERICAN" = "Asian",
  "NON-HISPANIC ASIAN" = "Asian",
  "ASIAN/PACIFIC ISLANDER" = "Asian",
  "ASIAN OR PACIFIC ISLANDER" = "Asian",
  "ASIAN/PACIFIC" = "Asian",
  "NON-HISPANIC ASIAN OR PACIFIC ISLANDER" = "Asian",
  "CHINESE"="Asian",
"NON-HISPANIC, ASIAN" = "Asian",
"ASIAN DONOR / NON-ASIAN RECIPIENT" = "Asian",
"ASIAN DONOR / ASIAN RECIPIENT" = "Asian",
"SOUTH ASIAN" = "Asian",
"ASIAN AND OTHER" = "Asian",
"ASIAN OR ASIAN AMERICAN" = "Asian",
"ASIAN/NHOPI" = "Asian",
"ASIAN, NON-HISPANIC" = "Asian",
"ASIAN AMERICAN AND PACIFIC ISLANDER" = "Asian",
"ASIAN/ASIAN AMERICAN" = "Asian"

)

aian <- c(
"AMERICAN INDIAN/ALASKA NATIVE" = "American Indian or Alaska Native",
"NON-HISPANIC AMERICAN INDIAN/ALASKA NATIVE" = "American Indian or Alaska Native",
"NON-HISPANIC NATIVE AMERICAN" = "American Indian or Alaska Native",
"AMERICAN INDIAN/ALASKA NATIVE" = "American Indian or Alaska Native",
"AMERICAN INDIAN/ALASKAN" = "American Indian or Alaska Native",
  "AMERICAN INDIAN, ALASKA NATIVE, AND NATIVE HAWAIIAN" = "American Indian or Alaska Native",
  "AMERICAN INDIAN OR ALASKA NATIVE" = "American Indian or Alaska Native",
  "AMERICAN INDIAN OR ALASKA NATIVE, NON-HISPANIC" = "American Indian or Alaska Native",
  "NATIVE AMERICAN" = "American Indian or Alaska Native",
  "NON-HISPANIC AMERICAN INDIAN" = "American Indian or Alaska Native",
  "INDIGENOUS AMERICAN" = "American Indian or Alaska Native",
  "AMERICAN INDIAN/ALASKAN NATIVE"="American Indian or Alaska Native",
  "AMERICAN INDIAN/ALASKA NATIVE"="American Indian or Alaska Native",
"INDIAN AMERICAN"="American Indian or Alaska Native",
"NATIVE AMERICAN OR ALASKAN NATIVE"="American Indian or Alaska Native"
)

other_unk <- c(
  "AMERICAN INDIAN"= "Other",
  "ALASKAN NATIVE"= "Other",
  "NON-HISPANIC AMERICAN INDIAN OR ALASKA NATIVE" = "Other",
  "AMERICAN INDIAN OR ALASKAN" = "Other",
  "INDIGENOUS" = "Other",
  "OTHER" = "Other",
  "OTHER RACE" = "Other",
  "OTHERS"="Other",
  "OTHER/UNKNOWN"="Other",
  "WHITE DONOR / NONWHITE RECIPIENT" = "Other",
  "NON WHITE" = "Other",
  "NON WHITE RACE" = "Other",
  "NON-WHITE" = "Other",
  "NON-BLACK" = "Other",
  "HBNO (HISPANIC, BLACK, NATIVE AMERICAN/ALASKAN AND OTHER)" = "Other",
  "NON-HISPANIC OTHER" = "Other",
  "NON-HISPANIC OTHER RACE" = "Other",
  "NON-HISPANIC, ALL OTHERS" = "Other",
  "OTHER OR MULTIPLE RACES, NON-HISPANIC" = "Other",
  "HISPANIC ETHNICITY" = "Other",
  "MULTIRACIAL" = "Other",
  "ADDITIONAL RACES AND ETHNICITIES OR MIXED" = "Other",
  "MULTIPLE OR OTHER" = "Other",
  "TWO OR MORE RACES" = "Other",
  "NON-HISPANIC OTHER-MULTI-RACE" = "Other",
  "OTHER OR MISSING" = "Other",
  "OTHER, MIXED, UNKNOWN" = "Other",
  "SOMALIA-BORN" = "Other",
  "AFRICAN-BORN BLACK" = "Other",
  "OTHER MINORITY" = "Other",
  "OTHER/MULTIRACIAL" = "Other",
  "MEXICAN/AMERICAN" = "Other",
  "OTHER RACES OR ETHNICITY" = "Other",
  "MULTIRACIAL OR OTHER" = "Other",
  "OTHER RACE-ETHNICITY" = "Other",

  "UNKNOWN"="Unknown",
  "NOT IDENTIFIED"="Unknown",
  "OTHER OR UNKNOWN"="Unknown",
  "OTHER OR ASIAN"="Unknown",
  "MULTIRACIAL"="Unknown",
  "MISSING"="Unknown",
  "OTHER/UNKNOWN"="Unknown",
  "MORE THAN ONE RACE"="Unknown",
"MULTIPLE RACES"="Unknown",
"NOT IDENTIFIED"="Unknown",
"UNKNOWN OR MISSING"="Unknown",
"NONE OF THE ABOVE"="Unknown",
"UNABLE TO DETERMINE"="Unknown",
"DECLINED OR UNKNOWN"="Unknown",
"NATIVE AMERICAN OR UNKNOWN"="Unknown",
"UNKNOWN/OTHER"="Unknown",
"OTHER/NOS/UNKNOWN"="Unknown",
  "OTHER/MISSING"="Unknown",
"ALL OTHER/UNKNOWN OR MISSING"="Unknown",
"RECIPIENTS MISSING RACE/ETHNICITY"="Unknown",
"UNAVAILABLE"="Unknown",
"OTHERS OR UNKNOWN"="Unknown",
"NONE OF THE ABOVE, MULTIPLE, OR UNKNOWN"="Unknown",
"DECLINED OR UNAVAILABLE"="Unknown",
"NONE OF THE ABOVE, NON-HISPANIC"="Unknown",
"UNKNOWN/NOT DOCUMENTED"="Unknown",
"ITEM MISSED OR SKIPPED"="Unknown",
"OTHER, MIXED, OR UNKNOWN"="Unknown"
)

nhpi <- c(
  "HAWAIIAN"="Native Hawaiian Or Pacific Islander",
"PACIFIC ISLANDER/HAWAIIAN"="Native Hawaiian Or Pacific Islander",
"NATIVE HAWAIIAN"="Native Hawaiian Or Pacific Islander",
"PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",
"NON-HISPANIC ASIAN/PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",
"NONHISPANIC ASIAN OR PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",
"NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",
"NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER, NON-HISPANIC"="Native Hawaiian Or Pacific Islander",
"HAWAIIAN/PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",
"NON-HISPANIC ASIAN AND PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",
"NATIVE HAWAIIAN OR PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",
"NATIVE HAWAIIAN/PACIFIC ISLANDER"="Native Hawaiian Or Pacific Islander",

"URM (BLACK, HISPANIC, NATIVE AMERICAN/ALASKAN, ASIAN/PACIFIC ISLANDER, AND OTHER)"="Uncategorized",
"WHITE/OTHER"="Uncategorized",
"SOUTH AND CENTRAL AMERICAN"="Uncategorized",
"PUERTO RICAN"="Uncategorized",
"MEXICAN"="Uncategorized",
"CUBAN"="Uncategorized",
"NONWHITE"="Uncategorized",
"NH OTHER"="Uncategorized",
"NON-HISPANIC, NONE OF THE ABOVE"="Uncategorized",
"NON-HISPANIC MIXED"="Uncategorized",
"AMERICAN INDIAN, ALASKA NATIVE, OR OTHER"="Uncategorized",
"ASIAN, NATIVE HAWAIIAN, OR PACIFIC ISLANDER"="Uncategorized",
"NATIVE"="Uncategorized",
"NH BLACK"="Uncategorized",
"OTHER (ASIAN, PACIFIC ISLANDER, NATIVE AMERICAN, MIXED OR OTHER)"="Uncategorized",
"NON AFRICAN AMERICAN"="Uncategorized",
"NON-AFRICAN AMERICAN"="Uncategorized",
"EUROPEAN AMERICANS"="Uncategorized",
"MINORITY"="Uncategorized"
)


race_mapping <- c(
  white,
  black,
  hispanic,
  asian,
  aian,
  other_unk,
  nhpi
)
race_columns <- c("race1", "race2", "race3", "race4", "race5", "race6", "race7", "race8")

# articles <- articles |>
#   mutate(clean_race = race_mapping[as.character(original_race_column)])

unique_race_values <- articles |>
  pivot_longer(cols = all_of(race_columns), names_to="race_column", values_to = "race_cleansed") |>
  mutate(race_cleansed=toupper(race_cleansed))

urvs <- unique_race_values[["race_cleansed"]]


```



```{r}
unique_race_values <- unique_race_values |>
   mutate(clean_race = race_mapping[as.character(race_cleansed)])


missing <- unique_race_values[!is.na(unique_race_values$race_cleansed) & is.na(unique_race_values$clean_race),] |> select(race_cleansed)

```


```{r}

endingcleansed <- unique_race_values |> 
  rowwise() |>
    mutate(race_value = cur_data()[[paste0(race_column, "_ss")]]) 
```



```{r}
data <- endingcleansed |> select(clean_race, race_value, journal, year) |> 
  filter(!is.na(clean_race) | !is.na(race_value))


aggregated_values <- data |> group_by(year, clean_race) |> summarise(
  total_counts = sum(race_value)
)

# we find that some values = -99, initial journal incorrect inputs

aggregated_values <- aggregated_values |> ungroup() |> filter(total_counts != -99)
```


```{r}

ggplot(aggregated_values, aes(x=year, y=total_counts, color=clean_race)) +
         geom_line()
```

```{r}
proportions <- aggregated_values |> 
  group_by(year, clean_race) |> 
  summarise(n = sum(total_counts)) |>
  mutate(freq = (n / sum(n)) * 100)
```

```{r}
proportions <- proportions |> filter(round(freq, 0) > 0)
ggplot(proportions, aes(x=year, y=freq, fill=clean_race)) +
         geom_col() + geom_text(aes(label=round(freq, 0)))


```

```{r}
# set width of code output
options(width = 65)
library(ggplot2)
library(scales)



# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 3,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300             # higher dpi, sharper image
)

ggplot(proportions, aes(x=year, y=freq, color=clean_race)) +
         geom_path(linewidth=1) + 
  labs(
    x="Year", y="Percentage of Total Population"
  ) 


```

```{r}
ggplot(proportions, aes(x=year, y=freq, color=clean_race)) +
         geom_path(linewidth=1) + 
  facet_wrap(vars(clean_race))
```

```{r}
tmp <- proportions %>%
  mutate(race2=clean_race)

tmp %>%
  ggplot( aes(x=year, y=freq)) +
    geom_line( data=tmp %>% select(-clean_race), aes(group=race2), color="lightgrey", size=0.5, alpha=0.5) +
    geom_line( aes(color=clean_race), color="darkolivegreen4", size=1.2 )+
    theme(
      legend.position="none",
      plot.title = element_text(size=14),
      panel.grid = element_blank()
    ) +
    facet_wrap(~clean_race) + 
  theme(
    panel.background=element_blank(),
    strip.background=element_rect(fill="snow2", color="snow3"),
    strip.clip="on"
  ) + 
  labs(
    title = "Comparison of proportional race disparities \nin gynecological studies, 2010-2023",
    y="Percentage", x="Year"
  )

# ref https://www.data-to-viz.com/caveat/spaghetti.html
```


```{r}
# comparison of study length 

article_lengths <- articles[c('study_year_start', 'study_year_end', 'journal')] |> 
  mutate(research_length = study_year_end - study_year_start) |>
  filter(!is.na(study_year_start) &
           study_year_start > 0 & study_year_end > 0 )

article_lengths_aggregated <- article_lengths |> 
  group_by(journal, study_year_start) |> summarise(
  mean = mean(research_length, rm.na=TRUE)
) |> filter(!is.na(study_year_start) & mean != 99 & abs(study_year_start) != 99 & 
              mean > 0)
```

```{r fig.width=10}
ggplot(article_lengths, aes(x=study_year_start, y=research_length, )) + 
  stat_density_2d(color="royalblue4") + 
  xlim(1990, 2026) + 
  ylim(-10, 20) + 
  facet_wrap(~journal, scales="free_x") + 
  labs(x="Starting Study Year", y="Research Length",
       title="Comparison of study lengths across gynecological journals")
  
```
```{r}
install.packages("showtext")
library(showtext)
install.packages("ggtext")
library(ggtext)
```


```{r}
p = ggplot(proportions, aes(fill = clean_race, values = freq)) +
  geom_waffle(color = "white", size = .25, n_rows = 10, flip = TRUE) +
  facet_wrap(~year, nrow = 1, strip.position = "bottom", scales="free_x") +
  scale_x_discrete() + 
  scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
                     expand = c(0,0))+
  labs(title = "Comparison of Race and Ethnicity over time\nin gynecological journals",
       caption = "Source: TidyTuesday")+
  theme_minimal() + 
  theme(strip.placement = "outside",
       panel.spacing.x = unit(.1, "lines"),
       ) + 
  guides(
    fill=guide_legend(title="Race/Ethnic Category")
  )
p
```

